services:
  python:
    build: .
    container_name: python
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    tty: true
    stdin_open: true
    networks:
      - edm-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - edm-network

volumes:
  mysql-data:

networks:
  edm-network:
    driver: bridge
